homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: !secret time_zone
  customize: !include customize.yaml

# 'default_config:' stuff minus a few things
config:
frontend:
history:
logbook:
map:
mobile_app:
person:
sun:
system_health:
updater:

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

camera:
  - platform: ring

discovery:
  ignore:
    - plex_mediaserver

http:
  base_url: !secret base_url
  server_port: !secret server_port
  ip_ban_enabled: True
  login_attempts_threshold: 5
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

lovelace:
  mode: yaml

ring:
  username: !secret ring_username
  password: !secret ring_password

sensor:
  - platform: ring

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config:
    light.living_room:
      refresh_value: true

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
