title: Home
theme: dark-mode
views:
  - icon: mdi:home-assistant
    title: Home
    cards:
      - type: entities
        title: Living Room
        entities:
          - light.living_room

      - type: picture-glance
        title: Front Door
        entities:
          - sensor.ring_front_door_last_activity
        camera_image: camera.front_door
