title: Home
theme: dark-mode
views:
  - icon: mdi:home-assistant
    title: Home
    cards:
      - type: entities
        title: Living Room
        show_header_toggle: false
        entities:
          - light.living_room

      - type: entities
        title: Exterior
        show_header_toggle: false
        entities:
          - switch.front_porch
